version: "3"
# services:
#   web:
#     build: .
#     command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
#     volumes:
#       - .:/code
#     ports:
#       - "8000:8000"
#     depends_on:
#       - my-postgres
#     environment:
#       - DATABASE_HOST=my-postgres
#       - DATABASE_PORT=5432
#       - DATABASE_NAME=postgres
#       - DATABASE_USER=postgres
#       - DATABASE_PASSWORD=algonetwork

#   my-postgres:
#     image: postgres
#     environment:
#       POSTGRES_PASSWORD: algonetwork
#     ports:
#       - "5432:5432"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=algonetwork
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=algonetwork
    ports:
      - "5432:5432"
