version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpassword
    ports:
      - "5432:5432"
