# Generated by Django 5.0.6 on 2024-06-07 00:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendingemail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
