# Generated by Django 5.0.6 on 2024-06-10 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendingemail', '0003_emailschedule_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailschedule',
            name='creator',
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='email_schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
