# Generated by Django 5.0.6 on 2024-06-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendingemail', '0004_remove_emailschedule_creator_emailschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailschedule',
            name='status_sent',
            field=models.BooleanField(default=False),
        ),
    ]
