# Generated by Django 5.0.6 on 2024-08-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0002_department_remove_emaildata_group_and_more'),
        ('sendingemail', '0005_emailschedule_status_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailschedule',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_schedules', to='email_data.department'),
        ),
    ]
