# Generated by Django 5.0.6 on 2024-06-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePromptMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('sendto', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=10)),
                ('modes', models.CharField(choices=[('Formal', 'Formal'), ('Informal', 'Informal'), ('Persuasive', 'Persuasive'), ('Standard', 'Standard'), ('Standard', 'Standard')], max_length=10)),
                ('maxwords', models.IntegerField()),
                ('detail_email', models.TextField(max_length=100)),
                ('messages', models.TextField()),
            ],
        ),
    ]
