# Generated by Django 5.0.6 on 2024-06-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('sendto', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=10)),
                ('mode', models.CharField(choices=[('Formal', 'Formal'), ('Informal', 'Informal'), ('Persuasive', 'Persuasive'), ('Standard', 'Standard'), ('Creative', 'Creative')], max_length=10)),
                ('max_words', models.IntegerField()),
                ('email_detail', models.TextField()),
                ('prompting_result', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CreatePromptMessages',
        ),
    ]
