# Generated by Django 5.0.6 on 2024-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_message', '0002_emailgenerator_delete_createpromptmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailgenerator',
            name='mode',
            field=models.CharField(choices=[('Formal', 'Formal'), ('Casual', 'Casual'), ('Persuasive', 'Persuasive'), ('Standard', 'Standard'), ('Creative', 'Creative')], max_length=10),
        ),
    ]
