# Generated by Django 5.0.6 on 2024-06-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator_message', '0003_alter_emailgenerator_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailGenerator',
        ),
    ]
