# Generated by Django 5.0.6 on 2024-05-30 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('HR', 'Devisi HR'), ('RnD', 'Devisi RnD'), ('Media', 'Devisi Media Informasi'), ('Engineering', 'Devisi Engineering'), ('Customers', 'Customers')], max_length=50)),
            ],
        ),
    ]
