# Generated by Django 5.0.6 on 2024-08-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0002_department_remove_emaildata_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_data', to='email_data.department'),
        ),
    ]
